### ISSUE TITLE
New ALTO schema versions to schema catalog

### ISSUE THREAD

**Issue by jukervin** [Digital-Preservation-Finland/dpres-xml-schemas#1]
schemas_external is missing newer ALTO schemas

https://www.loc.gov/standards/alto/v4/alto-4-3.xsd
https://www.loc.gov/standards/alto/v4/alto-4-2.xsd

**Comment by jmlehton** [comment]
Thank you for the issue. Newer ALTO schemas have been added now. See commit https://github.com/Digital-Preservation-Finland/dpres-xml-schemas/commit/b61686492005aae47bf6ae6804a578078dbc79c9
